language: java
jdk: openjdk11
sudo: false

services:
  - docker

script:
  <%_ if (buildTool === 'maven') { _%>
  - ./mvnw clean install
  <%_ } _%>
  <%_ if (buildTool === 'gradle') { _%>
  - ./gradlew clean build
  <%_ } _%>
