pipeline {
    agent any

    triggers {
            pollSCM('* * * * *')
    }

    environment {
        APPLICATION_NAME = '<%= appName %>'
    }

    stages {
        stage('Build') {
            steps {
                <%_ if (buildTool === 'maven') { _%>
                sh './mvnw clean verify'
                <%_ } _%>
                <%_ if (buildTool === 'gradle') { _%>
                sh './gradlew clean build'
                <%_ } _%>
            }
        }
    }
}
