name: Main Branch CI

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK <%= JAVA_VERSION %>
        uses: actions/setup-java@v3.1.1
        with:
          java-version: <%= JAVA_VERSION %>
          distribution: 'zulu'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build
