pipeline {
    agent any

    triggers {
            pollSCM('* * * * *')
    }

    environment {
        APPLICATION_NAME = 'spring-cloud-service-registry'
    }

    stages {
        stage('Build') {
            steps {
                sh './mvnw clean install'
            }
        }
    }
}
