<%_ if (databaseType === 'postgresql') { _%>
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/appdb
<%_ } _%>
<%_ if (databaseType === 'mysql') { _%>
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/appdb
<%_ } _%>
<%_ if (databaseType === 'mariadb') { _%>
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/appdb
<%_ } _%>
  datasource:
    username: appuser
    password: secret

<%_ if (features.includes('localstack')) { _%>
###AWS
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        secret-key: noop
        access-key: noop
      endpoint: http://localhost:4566
<%_ } _%>
