const LOCALSTACK_IMAGE_VERSION = '2.3.2';
const POSTGRESQL_IMAGE_VERSION = '16.0-alpine';
const MARIADB_IMAGE_VERSION = '11.0.3';
const MYSQL_IMAGE_VERSION = '8.2.0';

module.exports = {
    JAVA_VERSION: '17',
    SPRING_BOOT_VERSION: '3.1.5',
    SPRING_CLOUD_VERSION: '2022.0.4',
    SPRING_CLOUD_AWS_VERSION: '3.0.3',
    SPRING_DEP_MNGMNT_VERSION: '1.1.3',
    DEFAULT_APP_VERSION: '0.0.1-SNAPSHOT',
    SPRINGDOC_OPENAPI_VERSION: '2.2.0',
    COMMONS_IO_VERSION: '2.15.0',
    LOGSTASH_LOGBACK_ENCODER: 7.3,
    PALANTIR_JAVA_FORMAT_VERSION: '2.38.0',

    JACOCO_MIN_COVERAGE_REQUIRED: '0.80',

    GRADLE_GIT_PROPERTIES_PLUGIN_VERSION: '2.4.1',
    GRADLE_JACOCO_PLUGIN_VERSION: '0.8.10',
    GRADLE_SONAR_PLUGIN_VERSION: '4.3.0.3225',
    GRADLE_OWASP_PLUGIN_VERSION: '8.2.1',
    GRADLE_BENMANES_VERSIONS_PLUGIN_VERSION: '0.47.0',
    GRADLE_SPOTLESS_PLUGIN_VERSION: '6.21.0',

    MAVEN_DEPENDENCY_CHECK_PLUGIN_VERSION: '8.4.2',
    MAVEN_PROPERTIES_PLUGIN_VERSION: '1.2.1',
    MAVEN_SONAR_PLUGIN_VERSION: '3.10.0.2594',
    MAVEN_JACOCO_PLUGIN_VERSION: '0.8.11',
    MAVEN_SPOTLESS_PLUGIN_VERSION: '2.40.0',

    KEY_FLYWAY_MIGRATION_COUNTER: 'flywayMigrationCounter',
    KEY_LIQUIBASE_MIGRATION_COUNTER: 'liquibaseMigrationCounter',

    LOCALSTACK_IMAGE_VERSION: LOCALSTACK_IMAGE_VERSION,
    LOCALSTACK_IMAGE: 'localstack/localstack:' + LOCALSTACK_IMAGE_VERSION,

    POSTGRESQL_IMAGE_VERSION: POSTGRESQL_IMAGE_VERSION,
    POSTGRESQL_IMAGE: 'postgres:' + POSTGRESQL_IMAGE_VERSION,

    MARIADB_IMAGE_VERSION: MARIADB_IMAGE_VERSION,
    MARIADB_IMAGE: 'mariadb:' + MARIADB_IMAGE_VERSION,

    MYSQL_IMAGE_VERSION: MYSQL_IMAGE_VERSION,
    MYSQL_IMAGE: 'mysql:' + MYSQL_IMAGE_VERSION,
}
