const JAVA_VERSION = '11';
const SPRING_BOOT_VERSION = '2.4.1';
const SPRING_CLOUD_VERSION = '2020.0.0-RC1';
const SPRING_DEP_MNGMNT_VERSION = '1.0.10.RELEASE';
const DEFAULT_APP_VERSION = '0.0.1-SNAPSHOT';
const PROBLEM_SPRING_WEB_VERSION = '0.26.2';
const TEST_CONTAINERS_VERSION = '1.15.0';
const SWAGGER_VERSION = '3.0.0';

const KEY_FLYWAY_MIGRATION_COUNTER = 'flywayMigrationCounter';
const KEY_LIQUIBASE_MIGRATION_COUNTER = 'liquibaseMigrationCounter';

const constants = {
    JAVA_VERSION,
    SPRING_BOOT_VERSION,
    SPRING_CLOUD_VERSION,
    SPRING_DEP_MNGMNT_VERSION,
    DEFAULT_APP_VERSION,
    PROBLEM_SPRING_WEB_VERSION,
    TEST_CONTAINERS_VERSION,
    SWAGGER_VERSION,
    KEY_FLYWAY_MIGRATION_COUNTER,
    KEY_LIQUIBASE_MIGRATION_COUNTER
};

module.exports = constants;