module.exports = {
    JAVA_VERSION : '11',
    SPRING_BOOT_VERSION : '2.6.7',
    SPRING_CLOUD_VERSION : '2021.0.1',
    SPRING_CLOUD_AWS_VERSION : '2.4.0',
    SPRING_DEP_MNGMNT_VERSION : '1.0.11.RELEASE',
    DEFAULT_APP_VERSION : '0.0.1-SNAPSHOT',
    PROBLEM_SPRING_WEB_VERSION : '0.27.0',
    TEST_CONTAINERS_VERSION : '1.16.2',
    SPRINGDOC_OPENAPI_VERSION : '1.6.8',
    AWAITILITY_VERSION : '4.2.0',
    COMMONS_LANG_VERSION : '3.12.0',
    COMMONS_IO_VERSION : '2.11.0',

    JACOCO_MIN_COVERAGE_REQUIRED:'0.80',

    GRADLE_GIT_PROPERTIES_PLUGIN_VERSION:'2.4.0',
    GRADLE_JACOCO_PLUGIN_VERSION:'0.8.7',
    GRADLE_SONAR_PLUGIN_VERSION:'3.3',
    GRADLE_OWASP_PLUGIN_VERSION:'7.1.0.1',
    GRADLE_BENMANES_VERSIONS_PLUGIN_VERSION:'0.42.0',
    GOOGLE_JAVA_FORMAT_PLUGIN_VERSION:'0.9',

    MAVEN_DEPENDENCY_CHECK_PLUGIN_VERSION:'7.1.0',
    MAVEN_PROPERTIES_PLUGIN_VERSION:'1.1.0',
    MAVEN_FAILSAFE_PLUGIN_VERSION:'3.0.0-M6',
    MAVEN_SONAR_PLUGIN_VERSION:'3.9.1.2184',
    MAVEN_JACOCO_PLUGIN_VERSION:'0.8.8',
    MAVEN_SPOTLESS_PLUGIN_VERSION:'2.22.2',

    KEY_FLYWAY_MIGRATION_COUNTER : 'flywayMigrationCounter',
    KEY_LIQUIBASE_MIGRATION_COUNTER : 'liquibaseMigrationCounter'
}
